# Numpy

In [3]:
import numpy as np

In [7]:
#create simple array from the list

arr =  np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(arr)

numpy.ndarray

In [11]:
# Printing the dimension of an array 
arr.ndim

2

In [13]:
# for shape i.e it state the rows and columns in that array
arr.shape

(2, 3)

In [4]:
# for single making and single dimension 
arr2= np.array([[1,2,3]])
arr2

array([[1, 2, 3]])

In [20]:
print(arr2.ndim)
arr2.shape

2


(1, 3)

In [21]:
# creating (3,5) dimension array
arr3= np.array([[12,15,22,41,54],[51,58,52,74,36],[14,79,46,16,78]])

In [22]:
arr3

array([[12, 15, 22, 41, 54],
       [51, 58, 52, 74, 36],
       [14, 79, 46, 16, 78]])

In [23]:
arr3.ndim

2

In [25]:
arr3.shape

(3, 5)

In [29]:
# to check where the array is store
arr.data

# Random Sequence generator using numpy

In [30]:
from numpy import random

In [36]:
x= random.randint(100)
print(x)

52


In [43]:
# printing 5 rnadom number from the range of 1000
for i in range(0,5):
    print(random.randint(1000))

825
79
285
967
206


In [44]:
# Generating random float number
y= random.rand()
print(y)

0.8736589540490015


In [45]:
for i in range(0,5):
    print(random.rand())

0.2529778220336073
0.39598656453287007
0.9561657726843673
0.9705878802226433
0.4276889242869478


In [65]:
#creating the random array

z= random.randint(100,size=(5))
print(z)

[ 3 84  6  4 53]


In [66]:
# for and 2d array
w = random.randint(100,size=(3,5))
print(w)
print(w.shape)

[[72 14 64 51 71]
 [43 65 99  0 28]
 [42 86 14 81 61]]
(3, 5)


##  Practical --- Measurement for Central Tendency

In [67]:
import numpy as np
arr1=np.array([[15,96,14],[41,49,51]])
print(arr)

# for printing the minimum element in an array
print(np.amin(arr1))

# for printing the maximum element in an array
print(np.amax(arr1))

[[1 2 3]
 [4 5 6]]
14
96


In [75]:
# finding the mean , median , Standard Deviation and variance in numpy 

#mean --
print(np.mean(arr1))

#median--
print(np.median(arr1))

#for standard deviation--
print(np.std(arr1))

#for variance--
print(np.var(arr1))

44.333333333333336
45.0
27.469174642780143
754.5555555555555


## Practical- Array Broadcasting in numpy

In [78]:
# Various operation between the multiple array can be said as broad casting.
a= np.array([1.0,2.0,3.0])
b= np.array([2.0,5.0,4.0])
print(a+b)
print(a*b)
print(a/b)
print(a**b)

[3. 7. 7.]
[ 2. 10. 12.]
[0.5  0.4  0.75]
[ 1. 32. 81.]
